config/routes.rb
Bitspace::Application.routes.draw do

  resources :releases do
    collection do
      get :popular
      get :newest
    end
  end

  match '/now_playing' => 'tracks#now_playing'
  match '/scrobble' => 'tracks#scrobble'
  match '/love' => 'tracks#love'

  root :to => 'players#show'
  match '/popular' => 'players#show'
  match '/newest' => 'players#show'
  match '/:profile_id' => 'players#show'

end

app/views/admin/_menu.html.erb
<div class="grid_12 clearfix">
  <ul class="tabnav">
    <li><%= link_to('Status', admin_status_path, :class => request.path == admin_status_path ? 'current' : nil) %></li>
    <li><%= link_to('Jobs', admin_jobs_path, :class => request.path == admin_jobs_path ? 'current' : nil) %></li>
    <li><%= link_to('Users', admin_users_path, :class => request.path == admin_users_path ? 'current' : nil) %></li>
  </ul>
</div>

app/views/admin/index.html.erb
<div class="container_12 clearfix aligncenter">
  <%= render :partial => 'menu' %>
</div>

app/views/admin/jobs.html.erb
<% content_for :html_head do %>
<style type="text/css">
tr.failed td { text-decoration: line-through; }
tr.locked td { font-weight: bold; color: green; }
tr.backlog td { font-weight: bold; }
</style>
<% end %>
<div class="container_12 clearfix aligncenter">
  <%= render :partial => 'menu' %>
  <br style="clear:both;" />
  <table>
    <thead>
      <th class="grid_1">Priority</th>
      <th class="grid_1">Attempts</th>
      <th class="grid_3">Run at</th>
      <th class="grid_3">Created at</th>
      <th class="grid_1">Handler</th>
      <th class="grid_1">Last error</th>
      <th class="grid_2">Actions</th>
    </thead>
    <tbody>
      <% @jobs.each do |job| %>
      <tr class="<%= job_status_as_dom_class(job) %>">
        <td class="grid_1"><%= job.priority %></td>
        <td class="grid_1"><%= job.attempts %></td>
        <td class="grid_3"><%= job.run_at %></td>
        <td class="grid_3"><%= time_ago_in_words(job.created_at) %> ago</td>
        <td class="grid_1">
          <%= link_to('Show', "##{dom_id(job)}_handler", :rel => 'shadowbox') %>
          <div id="<%= dom_id(job) %>_handler" style="display:none;"><pre style="padding:20px;"><%=h job.handler %></pre></div>
        </td>
        <td class="grid_1">
          <%= link_to('Show', "##{dom_id(job)}_last_error", :rel => 'shadowbox') %>
          <div id="<%= dom_id(job) %>_last_error" style="display:none;"><pre style="padding:20px;"><%=h job.last_error %></pre></div>
        </td>
        <td class="grid_2">
          <%= link_to('Run now', admin_run_job_path(:id => job), :method => :post) %> &bull;
          <%= link_to('Delete', admin_delete_job_path(:id => job), :method => :delete) %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate(@jobs) %>
</div>
<script type="text/javascript">
Shadowbox.init();
</script>

app/views/admin/status.html.erb
<div class="container_12 clearfix aligncenter">
  <%= render :partial => 'menu' %>
  <br style="clear:both;" />
  <div class="grid_2">
    <dl class="status">
      <dt>Jobs in the queue</dt>
      <dd><%= link_to(Delayed::Job.count(:conditions => { :failed_at => nil }), admin_jobs_path) %></dd>
      <dt>Failed jobs</dt>
      <dd><%= Delayed::Job.count(:conditions => ['last_error IS NOT NULL']) %></dd>
      <dt>Retrying jobs</dt>
      <dd><%= Delayed::Job.count(:conditions => ['last_error IS NOT NULL AND failed_at IS NULL']) %></dd>
      <dt>Backlog</dt>
      <dd><%= Delayed::Job.count(:conditions => ['run_at <= ? AND failed_at IS NULL', Time.now.utc]) %></dd>
    </dl>
  </div>
  <div class="grid_2">
    <dl class="status">
      <dt>No. users</dt>
      <dd><%= link_to(User.count, admin_users_path) %></dd>
      <dt>Paying users</dt>
      <dd><%= User.count(:conditions => { :subscription_plan => User::SUBSCRIPTION_PLANS.values.select {|p| p[:price_in_euro] > 0 }.map {|p| p[:name] } }) %></dd>
      <dt>Free users</dt>
      <dd><%= User.count(:conditions => { :subscription_plan => User::SUBSCRIPTION_PLANS.values.select {|p| p[:price_in_euro] == 0 }.map {|p| p[:name] } }) %></dd>
      <dt>Paying ratio</dt>
      <dd><%= number_to_percentage((User.count(:conditions => { :subscription_plan => User::SUBSCRIPTION_PLANS.values.select {|p| p[:price_in_euro] > 0 }.map {|p| p[:name] } }).to_f / User.count.to_f) * 100.0, :precision => 1) %></dd>
    </dl>
  </div>
  <div class="grid_2">
    <dl class="status">
      <dt>Total storage</dt>
      <dd><%= number_to_human_size(Track.sum(:size)) %></dd>
      <dt>Total allowed storage</dt>
      <dd><%= number_to_human_size(User.sum(:max_storage)) %></dd>
      <dt>Real storage (approx.)</dt>
      <dd><%= number_to_human_size(Track.sum(:size, :group => 'fingerprint').values.sum) %></dd>
      <dt>Client downloads</dt>
      <dd><%= Client.all.inject(0) {|sum,x| sum += x.downloads } %></dd>
    </dl>
  </div>
  <div class="grid_2">
    <dl class="status">
      <dt>No. artists</dt>
      <dd><%= Artist.count %></dd>
    </dl>
  </div>
  <div class="grid_2">
    <dl class="status">
      <dt>No. releases</dt>
      <dd><%= Release.count %></dd>
      <dt>No. tracks</dt>
      <dd><%= Track.count %></dd>
    </dl>
  </div>
  <div class="grid_2">
    <dl class="status">
      <dt>SEK/month in (approx.)</dt>
      <dd><%= number_to_currency(approximate_revenue_in_sek, :unit => 'kr', :format => '%n %u') %></dd>
      <dt>SEK/month out (approx.)</dt>
      <dd><%= number_to_currency(approximate_cost_in_sek, :unit => 'kr', :format => '%n %u') %></dd>
      <dt>Bandwidth cost (approx.)</dt>
      <dd><%= number_to_currency(approximate_bandwidth_cost_in_sek, :unit => 'kr', :format => '%n %u') %></dd>
    </dl>
  </div>
</div>

app/views/admin/users.html.erb
<div class="container_12 clearfix aligncenter">
  <%= render :partial => 'menu' %>
  <br style="clear:both;" />
  <table>
    <thead>
      <th class="grid_1">Username</th>
      <th class="grid_3">E-mail</th>
      <th class="grid_1">Logins</th>
      <th class="grid_2">Last request</th>
      <th class="grid_1">Storage</th>
      <th class="grid_2">Subscription plan</th>
      <th class="grid_2">Created at</th>
    </thead>
    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td class="grid_1"><%= link_to(user.login || user.facebook_uid, user.login ? profile_path(user.login) : '#') %></td>
        <td class="grid_3">
          <%= link_to(user.email, "##{dom_id(user)}_handler", :rel => 'shadowbox') %>
          <div id="<%= dom_id(user) %>_handler" style="display:none;">
            <pre style="padding:20px; color:#fff;">E-mail: <%=h user.email %>
Login count: <%= user.login_count %>
Failed login count <%= user.failed_login_count %>
Last request: <%= user.last_request_at %>
Last login: <%= user.last_login_at %>
Last ip: <%= user.last_login_ip %>
Storage: <%= number_to_human_size(user.tracks.sum(:size)) %>
Max storage: <%= number_to_human_size(user.max_storage) %>
Subscriptin plan: <%= user.subscription_plan %>
Created: <%= user.created_at %>
Artists: <%= pluralize(user.artists.without_archived.has_releases.size, 'artists') %>
Releases: <%= pluralize(user.releases.without_archived.has_tracks.size, 'releases') %>
Tracks: <%= pluralize(user.tracks.size, 'tracks') %></pre>
          </div>
        </td>
        <td class="grid_1"><%= user.login_count %></td>
        <td class="grid_2"><%= time_ago_in_words(user.last_request_at) %> ago</td>
        <td class="grid_1"><%= number_to_human_size(user.tracks.sum(:size)) %></td>
        <td class="grid_2"><%= user.subscription_plan %></td>
        <td class="grid_2"><%= time_ago_in_words(user.created_at) %> ago</td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate(@users) %>
</div>
<script type="text/javascript">
Shadowbox.init();
</script>