config/routes.rb
Bitspace::Application.routes.draw do

  resources :releases do
    collection do
      get :popular
      get :newest
    end
  end

  match '/now_playing' => 'tracks#now_playing'
  match '/scrobble' => 'tracks#scrobble'
  match '/love' => 'tracks#love'

  root :to => 'players#show'
  match '/popular' => 'players#show'
  match '/newest' => 'players#show'
  match '/:profile_id' => 'players#show'

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  
  layout 'login', :only => [:credentials]
  
  def show
    respond_to do |format|
      format.html
      format.json
    end
  end
  
  def credentials
    if request.put?
      current_user.login = params[:user][:login]
      current_user.password = params[:user][:password]
      current_user.password_confirmation = params[:user][:password]
      if current_user.save
        redirect_to player_path(:trailing_slash => true)
      end
    end
  end
  
  def profile
    if request.put?
      if current_user.valid_password?(params[:password])
        current_user.email = params[:user][:email] if params[:user][:email].present?
        current_user.login = params[:user][:login] if params[:user][:login].present?
        current_user.password = params[:user][:password] if params[:user][:password].present?
        current_user.password_confirmation = params[:user][:password_confirmation] if params[:user][:password_confirmation].present?
        current_user.website = params[:user][:website] if params[:user][:website].present?
        current_user.biography = params[:user][:biography] if params[:user][:biography].present?
        current_user.public_profile = params[:user][:public_profile] if params[:user][:public_profile].present?
        if current_user.save
          head :ok
        else
          render :text => current_user.errors.full_messages.to_sentence, :status => :bad_request
        end
      else
        render :text => 'Invalid password', :status => :forbidden
      end
    end
  end
  
  def valid_password
    if current_user.valid_password?(params[:password])
      render :json => true
    else
      render :json => false
    end
  end
  
  def lastfm_scrobbling
    current_user.toggle!(:scrobble_to_lastfm)
    head :ok
  end
  
  def invitations
    @invitation = Invitation.new(params[:invitation])
    if request.post?
      @invitation.user = current_user
      @invitation.save!
      head :ok
    end
  end
  
  def status
    @since = Time.parse(params[:since])
    @nr_new_tracks = current_user.tracks.count(:conditions => ['created_at > ?', @since.utc])
    if @nr_new_tracks > 0
      render :text => "#{self.class.helpers.pluralize(@nr_new_tracks, 'new track')} added to your library."
    else
      head :ok
    end
  end
  
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_navigation.html.erb
<span class="member-since grey">
  Member since <%= current_user.created_at.to_date.to_formatted_s(:long) %>
</span>
<ul class="tabnav">
  <li><%= link_to('Overview', account_path, :target => '_self', :class => request.path == account_path ? 'current' : nil) %></li>
  <% unless ENV['PRIVATE_BETA'] %>
  <li><%= link_to('Upgrade', upgrade_account_path, :target => '_self', :class => request.path == upgrade_account_path ? 'current' : nil) %></li>
  <% end %>
  <li><%= link_to('Profile', profile_account_path, :target => '_self', :class => request.path == profile_account_path ? 'current' : nil) %></li>
  <li><%= link_to('Last.fm', lastfm_account_path, :target => '_self', :class => request.path == lastfm_account_path ? 'current' : nil) %></li>
</ul>

app/views/accounts/credentials.html.erb
<div class="container_16 clearfix">
  <div class="grid_8 prefix_4 suffix_4 aligncenter">
    
    <div class="box" id="account-credentials-box">
      <% if flash[:alert].present? %>
        <div class="bubble bubble-south">
          <div class="bubble-inner">
            <%=h flash[:alert] %>
          </div>
        </div>
      <% end %>
      
      <% if flash[:notice].present? %>
        <div class="bubble bubble-south">
          <div class="bubble-inner">
            <%=h flash[:notice] %>
          </div>
        </div>
      <% end %>
      
      <h1>Add credentials to your account</h1>
      <p>We are moving away from Facebook Connect. In preparation of the 
         public beta launch that will be announced soon, we are asking all 
         of our beta testers to add a username and password to their
         account. You will be using this username and password combination
         to sign in to Bitspace instead of your Facebook account
         from now on. We apologize for any inconveniences that this might
         cause and hope that you will continue to use and enjoy the service.
         <br /><br />
         Thank you!<br />
         The Bitspace Team</p>
      
      <% form_for current_user, :url => credentials_account_path,
                    :html => { :id => 'account-credentials-form' } do |f| %>
        <div class="field">
          <%= f.text_field :login, :class => 'required' %>
          <kbd>A username of your choice</kbd>
        </div>
        
        <div class="field">
          <%= f.password_field :password, :class => 'required' %>
          <kbd>A tricky password</kbd>
        </div>
        
        <div class="submit-row">
          <%= f.submit 'Save credentials' %>
        </div>
      <% end %>
      
      <p class="feedback">
        If you have any questions or feedback you can always contact us at
        <%= mail_to('beta@sutajio.se') %> or using the
        <%= link_to('support forum', 'http://getsatisfaction.com/bitspace') %>.</p>
    </div>
    
  </div>
</div>

app/views/accounts/invitations.html.erb
<div class="account" id="account-invitations">
  <div class="container_16 clearfix">
    <div class="pane clearfix">
      
      <div class="grid_9">
        <h3>Invite your friends to Bitspace</h3>
        <% if current_user.invitations_left.to_i > 0 %>
          <p class="grey">
            You can send an invitation by
            entering the email address of a friend below.
            Your friend will be invited to create a Bitspace Free
            account.
          </p>
          <p class="grey">You currently have <%= pluralize(current_user.invitations_left, 'invitation') %> left.</p>
          
          <% form_for @invitation, :url => invitations_account_path do |f| %>
            <p><%= f.text_field :email, :class => 'required email' %></p>
            <p><%= button_to('Send invitation', reset_api_token_account_path, :id => 'reset-api-token') %></p>
            <script type="text/javascript">
            $(function(){
              $('#new_invitation').validate({
                submitHandler: function(form) {
                  $(form).ajaxSubmit({
                    success: function(){
                      $.address.value('/');
                    }
                  });
                }
              });
            });
            </script>
          <% end %>
        <% else %>
          <p class="grey">
            <em>Sorry, you don't have any invitations left.</em>
          </p>
        <% end %>
        <% if current_user.invitations.present? %>
          <hr />
          <ul><% current_user.invitations.each do |invitation| %>
          <li class="grey"><code><%= link_to(invitation.token, invitation_path(invitation), :target => '_blank') %></code> &ndash;
            Was sent to <strong><%=h invitation.email %></strong></li>
          <% end %></ul>
        <% end %>
      </div>
      
    </div>
  </div>
</div>

app/views/accounts/lastfm.html.erb
<div class="account" id="account-lastfm">
  <div class="container_16 clearfix">
    <div class="pane clearfix">
      <%= render :partial => 'accounts/navigation' %>
      
      <hr />
      
      <div class="grid_8">
        <% if current_user.paying_customer? %>
          <% if current_user.connected_to_lastfm? %>
            <p class="lastfm-scrobbling-enabled"<%= ' style="display:none;"' unless current_user.scrobble_to_lastfm? %>>
              <%= image_tag('yes.png', :style => 'margin-bottom:-4px;') %>
              Last.fm scrobbling is currently enabled. <%= link_to('Disable it!', lastfm_scrobbling_account_path, :class => 'disable-lastfm-scrobbling') %>
            </p>
            <p class="lastfm-scrobbling-disabled"<%= ' style="display:none;"' if current_user.scrobble_to_lastfm? %>>
              <%= image_tag('no.png', :style => 'margin-bottom:-4px;') %>
              Last.fm scrobbling is currently disabled. <%= link_to('Enable it!', lastfm_scrobbling_account_path, :class => 'enable-lastfm-scrobbling') %>
            </p>
            <script type="text/javascript">
            $(function(){
              $('a.enable-lastfm-scrobbling').click(function(e){
                e.preventDefault();
                $.post(this.href, { '_method': 'put' }, function(){
                  $('.lastfm-scrobbling-enabled').show();
                  $('.lastfm-scrobbling-disabled').hide();
                });
              });
              $('a.disable-lastfm-scrobbling').click(function(e){
                e.preventDefault();
                $.post(this.href, { '_method': 'put' }, function(){
                  $('.lastfm-scrobbling-enabled').hide();
                  $('.lastfm-scrobbling-disabled').show();
                });
              });
            });
            </script>
          <% end %>
          <p class="grey">Click the button below to securely connect with your
          Last.fm account and enable scrobbling of the music you listen to in
          Bitspace. You wont have to give us your Last.fm password and we have
          no way of finding it out. The process is completely secure.
          <p class="grey">You can revoke access for the Bitspace
          application at any time by going to your Last.fm settings page,
          <%= link_to('here', 'http://last.fm/settings/applications', :class => 'external', :rel => 'shadowbox') %>.</p>
          <p><%= button_to('Connect with Last.fm', authorize_lastfm_path, :method => :get, :confirm => 'WARNING: You are about to leave Bitspace. This will stop your music and cancel all currently queued uploads. Do you want to continue?') %></p>
        <% else %>
          <p class="grey">Last.fm scrobbling is only available to paying customers.</p>
        <% end %>
      </div>
      
    </div>
  </div>
</div>

app/views/accounts/profile.html.erb
<div class="account" id="account-profile">
  <div class="container_16 clearfix">
    <div class="pane clearfix">
      <%= render :partial => 'accounts/navigation' %>
      
      <hr />
      
      <% form_for current_user, :url => profile_account_path,
                    :html => { :id => 'account-profile-form', :multipart => true } do |f| %>
        
        <div class="grid_8 alpha">
          <table>
            <tbody>
              <tr>
                <th><%= label_tag :password, 'Current password' %></th>
                <td>
                  <%= password_field_tag :password, '', :class => 'required' %>
                  <div class="hint"><%= link_to('Forgot your password?', forgot_password_path, :rel => 'shadowbox') %></div>
                </td>
              </tr>
              <tr>
                <th><%= f.label :email %></th>
                <td><%= f.text_field :email, :class => 'required email' %></td>
              </tr>
              <tr>
                <th><%= f.label :login, 'Username' %></th>
                <td><%= f.text_field :login, :class => 'required' %></td>
              </tr>
              <tr>
                <th><%= f.label :password, 'New password' %></th>
                <td><%= f.password_field :password %></td>
              </tr>
              <tr>
                <th><%= f.label :password_confirmation, 'Password again' %></th>
                <td><%= f.password_field :password_confirmation %></td>
              </tr>
              <tr>
                <th><%= f.label :avatar, 'Avatar' %></th>
                <td><%= f.file_field :avatar %></td>
              </tr>
            </tbody>
          </table>
        </div>
        <div class="grid_8 omega" style="border-left:2px solid #262626; width:458px;">
          <table>
            <tbody>
              <tr>
                <th><%= f.label :website %></th>
                <td>
                  <%= f.text_field :website, :class => 'url' %>
                </td>
              </tr>
              <tr>
                <th valign="top"><%= f.label :biography %></th>
                <td>
                  <%= f.text_area :biography, :size => '28x7', :style => 'display:block;' %>
                </td>
              </tr>
              <tr>
                <th></th>
                <td>
                  <%= f.check_box :public_profile %>
                  <%= f.label :public_profile, 'Enable my public profile' %>
                  <p id="whatispublicprofiles" class="grey" style="width:290px;">
                    Your public profile is a way for you to share your music taste and to let your friends follow
                    what you upload and listen to. You can find your public profile at: <%= link_to(profile_url(current_user.login), profile_url(current_user.login), :target => '_blank') %>
                  </p>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
        
        <hr />
        <p class="alignright"><%= submit_tag 'Save changes' %></p>
        
      <% end %>
    </div>
  </div>
</div>

app/views/accounts/show.html.erb
<div class="account" id="account">
  <div class="container_16 clearfix">
    <div class="pane clearfix">
      <%= render :partial => 'accounts/navigation' %>
      
      <hr />
      
      <div class="aligncenter">
      
        <h2>
          <%= current_user.subscription_plan %><br />
          <span><%= number_to_human_size(current_user.tracks.sum(:size)) %> /
          <%= number_to_human_size(current_user.max_storage) || 'Unlimited' %>
          <% unless ENV['PRIVATE_BETA'] %>
            <br /><br />
            <%= link_to('Click here if you need to upgrade!', upgrade_account_path, :target => '_self') %></span>
          <% end %>
        </h2>
        
        <div class="storage-gauge">
          <div class="storage-amount" style="width:<%= current_user.storage_used_in_percent %>%"></div>
        </div>
        
        <dl class="status grid_2 prefix_3 alpha">
          <dt>Artists</dt>
          <dd><%= current_user.artists.without_archived.has_releases.size %></dd>
        </dl>
        <dl class="status grid_2">
          <dt>Releases</dt>
          <dd><%= current_user.releases.without_archived.has_tracks.size %></dd>
        </dl>
        <dl class="status grid_2">
          <dt>Tracks</dt>
          <dd><%= current_user.tracks.size %></dd>
        </dl>
        <dl class="status grid_2 suffix_3 omega">
          <dt>Total time</dt>
          <dd><%= seconds_to_time(current_user.tracks.sum(:length)) %></dd>
        </dl>
      
      </div>
      
    </div>
  </div>
</div>

app/views/accounts/show.json.erb
<%= {
  :name => current_user.name,
  :website => current_user.website,
  :biography => current_user.biography,
  :login => current_user.login,
  :login_count => current_user.login_count,
  :account_type => current_user.account_type,
  
  :subscription_plan => current_user.subscription_plan,
  :max_storage => current_user.max_storage,
  :storage_left => current_user.storage_left,
  :storage_used => current_user.storage_used,
  :storage_used_in_percent => current_user.storage_used_in_percent,
  :paying_customer => current_user.paying_customer?,
  :distributor => current_user.distributor?,
  
  :artists_count => current_user.artists.without_archived.has_releases.size,
  :releases_count => current_user.releases.without_archived.has_tracks.size,
  :tracks_count => current_user.tracks.size,
  :followers_count => current_user.followers.size,
  :subscribers_count => current_user.subscribers.size,
  :total_time => seconds_to_time(current_user.tracks.sum(:length)),
  
  :subscriptions => current_user.memberships.map {|subscription|
    {
      :name => subscription.user.name || subscription.user.login,
      :url => profile_url(subscription.user.login)
    }
  }
}.to_json %>

app/views/accounts/upgrade.html.erb
<div class="account" id="account-upgrade">
  <div class="container_16 clearfix">
    <div class="pane clearfix">
      <%= render :partial => 'accounts/navigation' %>
      
      <hr />
      
      <div class="grid_16 alpha">
        <table class="subscriptions-chart">
          <thead>
            <th>Subscription plan</th>
            <th>Storage</th>
            <th>Albums</th>
            <th>Tracks</th>
            <th><span title="Professional grade global Content Delivery Network for low latency streaming." class="tooltipped help">CDN</span></th>
            <th><span title="Support for scrobbling played tracks to your Last.fm account." class="tooltipped help">Last.fm</span></th>
            <th><span title="Personal technical email support during office hours." class="tooltipped help">Support</span></th>
            <th></th>
            <th></th>
          </thead>
          <tbody>
            <% User::SUBSCRIPTION_PLANS.values.sort_by {|plan| plan[:price_in_euro].to_i }.reverse.each do |plan| %>
              <% if plan[:official] && plan[:price_in_euro] != 0 %>
                <tr>
                  <th>
                    <%= plan[:name] %><br />
                    <span class="grey"><%= number_to_currency(plan[:price_in_euro], :unit => '€') %>/month</span>
                  </th>
                  <td><%= number_to_human_size(plan[:storage]) || 'Unlimited' %></td>
                  <td><%= bytes_to_albums(plan[:storage]) %></td>
                  <td><%= bytes_to_tracks(plan[:storage]) %></td>
                  <td><%= image_tag('check.png') if plan[:price_in_euro] > 0 %></td>
                  <td><%= image_tag('check.png') if plan[:price_in_euro] > 0 %></td>
                  <td><%= image_tag('check.png') if plan[:price_in_euro] > 0 %></td>
                  <td><em><%= plan[:tagline] %></em></td>
                  <td>
                    <% if current_user.subscription_plan == plan[:name] %>
                      <strong>Your current plan</strong>
                    <% elsif plan[:paypal_button_id] == nil %>
                      <%= button_to(plan[:storage] > (current_user.max_storage || 1.0/0) ? 'Upgrade' : 'Downgrade', "https://www.paypal.com/cgi-bin/webscr?cmd=_subscr-find&alias=#{URI.encode(ENV['PAYPAL_USERNAME'])}", :confirm => 'WARNING: You are about to leave Bitspace. This will stop your music and cancel all currently queued uploads. Do you want to continue?') %>
                    <% else %>
                      <form action="https://www.paypal.com/cgi-bin/webscr" method="post">
                        <input type="hidden" name="cmd" value="_s-xclick" />
                        <input type="hidden" name="hosted_button_id" value="<%= plan[:upgrade_button_id] %>" />
                        <input type="hidden" name="modify" value="1" />
                        <%= submit_tag plan[:storage] > (current_user.max_storage || 1.0/0) ? 'Upgrade' : 'Downgrade', :confirm => 'WARNING: You are about to leave Bitspace. This will stop your music and cancel all currently queued uploads. Do you want to continue?' %>
                      </form>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
      
      <hr />
      
      <div class="grid_4 alpha grey">
        <strong>Need to cancel your account?</strong>
        <p>You can cancel your account at any time by clicking the link below.
        Your account will automatically be downgraded to a free account when you cancel.
        Please contact us if you want us to completely remove your account.
        <%= link_to('Cancel my account', "https://www.paypal.com/cgi-bin/webscr?cmd=_subscr-find&alias=#{URI.encode(ENV['PAYPAL_USERNAME'])}", :confirm => 'WARNING: You are about to leave Bitspace. This will stop your music and cancel all currently queued uploads. Do you want to continue?', :class => 'external') %></p>
      </div>
      
      <div class="grid_4 grey">
        <strong>What happens when I downgrade or cancel my subscription?</strong>
        <p>You will be given 14 days to delete enough releases from your
        library to fullfil your new quota. If you haven't deleted enough
        releases by that date we will automatically delete releases for you
        starting with archived and old releases.</p>
      </div>
      
      <div class="grid_4 grey">
        <strong>What happens if I upgrade or downgrade in the middle of a billing cycle?</strong>
        <p>If you upgrade or downgrade you'll be charged the new rate for your
        new plan starting from the date you upgrade. You currently need to manually cancel
        your old subscription yourself if you have one.</p>
      </div>
      
      <div class="grid_4 omega grey">
        <strong>We accept...</strong>
        <%= image_tag('paypal.png', :style => 'float:right;') %>
        <p>Visa, American Express, Mastercard, and any other payment method supported by PayPal. We don't accept checks, invoices, or POs, sorry.</p>
      </div>
      
    </div>
  </div>
</div>